"""Phase C — reportlab PDF for the TradePath customs amendment brief."""
from __future__ import annotations

import io
import re
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


_INVALID_FILENAME_CHARS = re.compile(r"[^A-Za-z0-9._-]+")


def safe_pdf_filename(seed: str) -> str:
    base = _INVALID_FILENAME_CHARS.sub("-", (seed or "shipment").strip()).strip("-")
    return f"tradepath-amendment-{base[:60] or 'shipment'}.pdf"


def _styles():
    base = getSampleStyleSheet()
    base.add(ParagraphStyle(
        name="TpTitle", parent=base["Title"], fontSize=18, leading=22,
        textColor=colors.HexColor("#1a4d7a"),
    ))
    base.add(ParagraphStyle(
        name="TpSection", parent=base["Heading2"], fontSize=13, leading=16,
        textColor=colors.HexColor("#1a4d7a"), spaceBefore=12, spaceAfter=4,
    ))
    base.add(ParagraphStyle(
        name="TpBody", parent=base["BodyText"], fontSize=10, leading=14,
    ))
    base.add(ParagraphStyle(
        name="TpQuote", parent=base["BodyText"], fontSize=10, leading=14,
        leftIndent=12, textColor=colors.HexColor("#555555"), italic=True,
    ))
    base.add(ParagraphStyle(
        name="TpFlag", parent=base["BodyText"], fontSize=10, leading=14,
        textColor=colors.HexColor("#9c1f1f"),
    ))
    return base


def render_amendment_brief_pdf(
    *,
    shipment: Dict[str, Any],
    transcript: Optional[str],
    voice_claims: Dict[str, Any],
    document_state: Dict[str, Any],
    contradictions: List[Dict[str, Any]],
    missing_evidence: List[Dict[str, Any]],
    talking_points: List[Dict[str, Any]],
    narrative: Optional[str],
    generated_by: str,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
        title="TradePath customs amendment brief",
        author=generated_by,
    )
    s = _styles()
    story: list = []

    story.append(Paragraph("Customs Amendment Brief — TradePath AI", s["TpTitle"]))
    story.append(Spacer(1, 6))

    # Shipment metadata
    meta = [
        ["Reference #", str(shipment.get("reference_number") or "—")],
        ["Origin", str(shipment.get("origin_country") or "—")],
        ["Destination", str(shipment.get("destination_country") or "—")],
        ["Exporter", str(shipment.get("exporter_name") or "—")],
        ["Importer", str(shipment.get("importer_name") or "—")],
        ["Status", str(shipment.get("status") or "—")],
        ["Generated by", generated_by],
    ]
    tbl = Table(meta, colWidths=[1.6 * inch, 4.8 * inch])
    tbl.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e6eef5")),
        ("BOX", (0, 0), (-1, -1), 0.4, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 10))

    # Voice amendment verbatim
    story.append(Paragraph("Agent Voice Amendment (verbatim)", s["TpSection"]))
    story.append(Paragraph(transcript or "<i>No voice amendment recorded for this shipment.</i>", s["TpQuote"]))

    if narrative:
        story.append(Paragraph("Customs-Audit Narrative", s["TpSection"]))
        story.append(Paragraph(narrative, s["TpBody"]))

    # Voice claims vs document state
    story.append(Paragraph("Voice Claims vs Record State", s["TpSection"]))
    claims_table = [
        ["Field", "Voice claim", "Existing record"],
        ["HS codes", ", ".join(voice_claims.get("hs_codes") or []) or "—",
         ", ".join((document_state.get("line_item_hs_codes") or []) +
                   (document_state.get("document_hs_codes") or [])) or "—"],
        ["Declared values (USD)", ", ".join(str(v) for v in voice_claims.get("values_usd") or []) or "—",
         ", ".join(str(v) for v in document_state.get("line_item_values_usd") or []) or "—"],
        ["Quantities", ", ".join(f"{q['qty']} {q['unit']}" for q in voice_claims.get("quantities") or []) or "—",
         ", ".join(f"{q.get('qty')} {q.get('unit')}" for q in document_state.get("quantities") or []) or "—"],
        ["Origins (ISO)", ", ".join(voice_claims.get("origins") or []) or "—",
         ", ".join(document_state.get("origins") or []) or "—"],
    ]
    ctbl = Table(claims_table, colWidths=[1.4 * inch, 2.5 * inch, 2.5 * inch])
    ctbl.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e6eef5")),
        ("BOX", (0, 0), (-1, -1), 0.4, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(ctbl)

    # Contradictions
    story.append(Paragraph("Contradictions", s["TpSection"]))
    if contradictions:
        for c in contradictions:
            story.append(Paragraph(
                f"<b>{c.get('type','contradiction').replace('_',' ').title()}</b> "
                f"({c.get('severity','high')})",
                s["TpFlag"],
            ))
            story.append(Paragraph(c.get("description", ""), s["TpBody"]))
    else:
        story.append(Paragraph("No material contradictions detected.", s["TpBody"]))

    # Missing evidence
    story.append(Paragraph("Missing Evidence", s["TpSection"]))
    if missing_evidence:
        for m in missing_evidence:
            story.append(Paragraph(
                f"<b>{m.get('claim','claim').replace('_',' ').title()}</b>",
                s["TpBody"],
            ))
            story.append(Paragraph(m.get("note", ""), s["TpBody"]))
    else:
        story.append(Paragraph("All voice claims supported by line items or OCR-extracted document fields.",
                               s["TpBody"]))

    # Talking points
    story.append(PageBreak())
    story.append(Paragraph("Customs-Audit Talking Points", s["TpSection"]))
    if talking_points:
        for tp in talking_points:
            story.append(Paragraph(
                f"<b>[{tp.get('topic','general').replace('_',' ')} • {tp.get('severity','info')}]</b> "
                + tp.get("point", ""),
                s["TpBody"],
            ))
    else:
        story.append(Paragraph("No talking points generated.", s["TpBody"]))

    doc.build(story)
    return buf.getvalue()
